# Generated by Django 2.0 on 2022-03-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
    ]
