# Generated by Django 2.0 on 2022-03-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20220309_2036'),
    ]

    operations = [
    ]
