# Generated by Django 2.0 on 2022-03-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20220309_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='banners',
            field=models.ImageField(null=True, upload_to='type1', verbose_name='商品侧翼图片'),
        ),
    ]
