# Generated by Django 2.0 on 2022-04-06 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussiness', '0006_bussiness_persondate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('feedbackContent', models.TextField(verbose_name='反馈问题')),
                ('feedbackAnswer', models.TextField(verbose_name='内容')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussiness.Bussiness', verbose_name='所属商家')),
            ],
            options={
                'verbose_name': '反馈表',
                'verbose_name_plural': '反馈表',
                'db_table': 'df_feedback',
            },
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('publicNumber', models.CharField(max_length=36, verbose_name='公告编号')),
                ('publicTitle', models.CharField(max_length=256, verbose_name='公告标题')),
                ('publicContent', models.TextField(verbose_name='公告内容')),
            ],
            options={
                'verbose_name': '公告表',
                'verbose_name_plural': '公告表',
                'db_table': 'df_public',
            },
        ),
    ]
