# Generated by Django 2.0 on 2022-04-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbackAnswer',
            field=models.TextField(default='', verbose_name='内容'),
        ),
    ]
