# Generated by Django 2.0 on 2022-04-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordersons'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='business',
            field=models.CharField(default='', max_length=20, verbose_name='商家ID'),
        ),
    ]
