# Generated by Django 2.0 on 2022-04-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=80, verbose_name='店铺名称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('addr', models.CharField(default='', max_length=256, verbose_name='店铺地址')),
                ('email', models.CharField(default='', max_length=56, verbose_name='邮箱地址')),
                ('signature', models.CharField(default='', max_length=256, verbose_name='店铺宣言')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
                'db_table': 'df_bussiness',
            },
        ),
    ]
