# Generated by Django 2.0 on 2022-04-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='是否激活'),
        ),
    ]
