# Generated by Django 2.0 on 2022-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0002_bussiness_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='accountRelate',
            field=models.CharField(default='无', max_length=30, verbose_name='账号关联'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='emailRemind',
            field=models.CharField(default='否', max_length=5, verbose_name='邮件提醒'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='kinds',
            field=models.CharField(default='无', max_length=256, verbose_name='店铺经营种类'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='personAccountRelate',
            field=models.CharField(default='无', max_length=30, verbose_name='联系人账号关联'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='personAddr',
            field=models.CharField(default='无', max_length=256, verbose_name='联系人地址地址'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='personAge',
            field=models.CharField(default='无', max_length=10, verbose_name='联系人年龄'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='personDescription',
            field=models.CharField(default='无', max_length=256, verbose_name='联系人信息描述'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='personEmailRemind',
            field=models.CharField(default='否', max_length=5, verbose_name='联系人邮件提醒'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='personName',
            field=models.CharField(default='无', max_length=30, verbose_name='联系人姓名'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='personSex',
            field=models.CharField(default='无', max_length=10, verbose_name='联系人性别'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='addr',
            field=models.CharField(default='无', max_length=256, verbose_name='店铺地址'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='email',
            field=models.CharField(default='无', max_length=56, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='signature',
            field=models.CharField(default='无', max_length=256, verbose_name='店铺宣言'),
        ),
    ]
