# Generated by Django 2.0 on 2022-04-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0003_auto_20220402_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='image',
            field=models.ImageField(default='', upload_to='dian', verbose_name='图片路径'),
        ),
        migrations.AddField(
            model_name='bussiness',
            name='personImage',
            field=models.ImageField(default='', upload_to='dian_person', verbose_name='图片路径'),
        ),
    ]
