# Generated by Django 2.0 on 2022-04-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0004_auto_20220402_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='personEmail',
            field=models.CharField(default='无', max_length=56, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='personAddr',
            field=models.CharField(default='无', max_length=256, verbose_name='联系人地址'),
        ),
    ]
