# Generated by Django 2.0 on 2022-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0005_auto_20220402_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='personDate',
            field=models.CharField(default='无', max_length=50, verbose_name='联系人生日'),
        ),
    ]
