# Generated by Django 2.0 on 2022-04-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0006_bussiness_persondate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='image',
            field=models.ImageField(default='group1/M00/00/01/rB58N2JIAz6AEi9rAAIlyVsSju03648559', upload_to='dian', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='personImage',
            field=models.ImageField(default='group1/M00/00/01/rB58N2JIAz6AEi9rAAIlyVsSju03648559', upload_to='dian_person', verbose_name='图片路径'),
        ),
    ]
